import React, { useEffect } from "react";
import SampleIcon from "../../assets/img/sample-icon.jpg";
import IconHeartGray from "../../assets/img/icon-heart-gray.svg";
import IconHeartTwitterBlue from "../../assets/img/icon-heart-twitterblue.svg";
import IconSmallMenu from "../../assets/img/icon-small-menu.svg";
import { deleteTweet } from "../../reducks/tweets/operations";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { push } from "connected-react-router";
import TimeAgo from "javascript-time-ago";
import ReactTimeAgo from "react-time-ago";
import en from "javascript-time-ago/locale/en";
import API from "../../API";